-- CRIA TABELA USUARIO
CREATE TABLE usuario (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    nome     VARCHAR(150) NOT NULL,
    email    VARCHAR(150) NOT NULL UNIQUE,
    senha    VARCHAR(255) NOT NULL,
    role     VARCHAR(30)  NOT NULL,
    situacao VARCHAR(20)  NOT NULL
);